name=AS7343_7Semi
version=1.0.0
author=Supratik Das
maintainer=supratikd <supratikdas@hotmail.com>
sentence=Arduino library for 7Semi AS7343 sensor board (OSRAM-AS7343).
paragraph=Supports 14 channels spectral data.
category=Sensors
url=https://github.com/supratikd/7Semi_AS7343
architectures=*
license=MIT