name=AS7343_7Semi
version=1.0.0
author=Supratik Das
maintainer=supratikd <supratikdas@hotmail.com>
sentence=Arduino library for the 7Semi AS7343 spectral sensor.
paragraph=Reads 12 spectral channels and VIS and NIR data, controls the LED, and detects flicker.
category=Sensors
url=https://github.com/supratikd/AS7343_7Semi
architectures=*
license=MIT